analyzer:
  enable-experiment:
    - non-nullable
  exclude:
    - lib/src/core/timezone.g.dart
    - lib/src/locale/locale.g.dart
linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - unnecessary_const
    - prefer_conditional_assignment
    - prefer_if_null_operators
    - prefer_null_aware_operators
    - prefer_relative_imports
    - hash_and_equals
    - valid_regexps
    - annotate_overrides
    - avoid_shadowing_type_parameters
    - cascade_invocations
    - directives_ordering
    - file_names
    - implementation_imports
    - join_return_with_assignment
    - prefer_adjacent_string_concatenation
    - prefer_foreach
    - prefer_final_in_for_each
    - prefer_generic_function_type_aliases
    - prefer_inlined_adds
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - slash_for_doc_comments
    - type_annotate_public_apis
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_this
    - use_rethrow_when_possible
    - comment_references