name: clockwork
description: Dart datetime library.

version: 0.0.1

environment:
  sdk: '>=2.8.0-dev.0 < 2.8.0'

dependencies:
  json_annotation:
  clockwork_gregorian_calendar:
    path: ../clockwork-gregorian-calendar

dev_dependencies:
  json_serializable:
  build_runner: